---
- name: Check if Django project directory exists
  stat:
    path: /home/vagrant/projectdir/static/
  register: stat_result

- name: Create and Configure a Django project
  command: > 
          chdir=/home/vagrant/projectdir/
          django-admin.py startproject testproject .
  when: not stat_result.stat.exists

- name: Adjust the ALLOWED_HOSTS project settings
  replace:
    path: /home/vagrant/projectdir/testproject/settings.py
    regexp: '(\s+)ALLOWED_HOSTS(\s+.*)?$'
    replace: '\nALLOWED_HOSTS = [ "*", "localhost", "192.168.60.4" ]'
    backup: yes 
    
- name: Add static directory setting
  lineinfile:
    path: /home/vagrant/projectdir/testproject/settings.py
    backup: yes
    regexp: '^STATIC_ROOT '
    insertafter: '^STATIC_URL '
    line: 'STATIC_ROOT =  BASE_DIR / "static"'
  